config/routes.rb
Rails.application.routes.draw do
  resources :records do
    resources :tags
  end

  devise_for :users

  get "search", to: "explore#search"

  root to: "explore#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/descriptive.rb
class Descriptive < ApplicationRecord
  has_many :free_tags
end

app/models/free_tag.rb
class FreeTag < ApplicationRecord
  belongs_to :record
  belongs_to :descriptive
  belongs_to :user

  delegate :term, to: :descriptive
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :free_tags

  has_many :descriptives, through: :free_tags

  has_many :scale_tags
end

app/models/scale.rb
class Scale < ApplicationRecord
  has_many :scale_tags
end

app/models/scale_tag.rb
class ScaleTag < ApplicationRecord
  belongs_to :record
  belongs_to :scale
  belongs_to :user

  delegate :left, :right, to: :scale, prefix: :scale
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :records
  has_many :free_tags
  has_many :scale_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  layout 'vue', only: :index

  def index
  end

  def search
    @records = RecordSearcher.call(free_tags: params[:free_tags])
    @free_tags = FreeTagDecorator.call(@records, params[:free_tags])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    @record.user = current_user

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, :creator, :url)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_record

  def index
  end

  def new
  end

  def create
    FreeTagger.call(@record, tags_params[:free_tags], current_user)
    NewDescriptiveTagger.call(@record, tags_params[:new_descriptives], current_user)
    ScaleTagger.call(@record, tags_params[:scale_tags], current_user)
    NewScaleTagger.call(@record, tags_params[:scale_tags], current_user)
    redirect_to record_tags_path(@record)
  end

  private
    def set_record
      @record = Record.find(params[:record_id])
    end

    def tags_params
      params.require(:tags).permit(:free_tags, :new_descriptives, :scale_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/explore/index.html.erb
<div id="explorer">
  <free-tag
    v-for="tag in freeTags"
    v-bind:key="'tag-' + tag.id"
    v-bind:tag="tag"
    v-on:filter="filterByFreeTag">
  </free-tag>

  <record
    v-for="record in records"
    v-bind:key="'record-' + record.id"
    v-bind:record="record">
  </record>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagger</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'hello_vue' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |type, notice| %>
        <div class="alert <%= type == 'alert' ? 'alert-danger' : 'alert-primary' %>">
          <%== notice %>
        </div>
      <% end %>
      <%= yield %>
      <br>
      <%= link_to 'go home', root_path %>
    </div>
  </body>
</html>

app/views/layouts/vue.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagger</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'explorer' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :record_title %>
  </div>

  <div class="field">
    <%= form.label :creator %>
    <%= form.text_field :creator, id: :record_creator %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :record_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Records</h1>

<% @records.each do |record| %>
  <div class="record card">
    <div class="card-body">
      <h5 class="card-title"><%= record.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= record.creator %></h6>
      <%= link_to 'Link', record.url, class: "btn btn-primary card-link" %>
      <%= link_to 'Show tags', record_tags_path(record), class: "card-link" %>
      <%= link_to 'Edit', edit_record_path(record), class: "card-link" %>
      <%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link" %>
    </div>
  </div>
<% end %>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @record.title %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @record.creator %>
</p>

<p>
  <strong>Url:</strong>
  <%= @record.url %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/tags/_free_tags_form.html.erb
<h3>Free tags:</h3>
<div>
  <% Descriptive.all.each do |desc| %>
    <span class="btn btn-secondary free-tag-button" data-descriptive-id='<%= desc.id %>'><%= desc.term %></span>
  <% end %>
</div>

<%= f.hidden_field :free_tags %>
<div class="form-group">
  <%= f.text_field :new_descriptives, placeholder: 'New terms (semicolon seperated)', class: "form-control" %>
</div>

<script type="text/javascript">
  var freeTagIds = [];

  $('.free-tag-button').click(function() {
    var descId = $(this).data('descriptiveId').toString();
    if (freeTagIds.indexOf(descId) == -1) {
      freeTagIds.push(descId);
      $(this).addClass('active');
    } else {
      freeTagIds = freeTagIds.filter(id => id !== descId);
      $(this).removeClass('active');
    }
    $('input#tags_free_tags').val(freeTagIds);
  });
</script>

app/views/tags/_scale.html.erb
<% [[-1,'++'],[-0.5,'+'],[0,'0'],[0.5,'+'],[1,'++']].each do |val, text| %>
  <span class="btn btn-secondary scale-tag-button"
        data-scale-id="<%= scale_id %>"
        data-scale-value="<%= val %>"
  ><%= text %></span>
<% end %>

app/views/tags/_scale_tags_form.html.erb
<h3>Scale tags:</h3>

<div class="text-center">
  <% Scale.all.each do |scale| %>
    <div class="tag-scale">
      <%= scale.left %>
      <%= render 'scale', scale_id: scale.id %>
      <%= scale.right %>
    </div>
  <% end %>
  <div class="tag-scale">
    <%= text_field_tag :new_scale_left, nil,
        placeholder: 'New scale left term',
        class: "new-scale-term",
        data: {'scale-side' => 'left'} %>
    <%= render 'scale', scale_id: 'new' %>
    <%= text_field_tag :new_scale_right, nil,
        placeholder: 'New scale right term',
        class: "new-scale-term",
        data: {'scale-side' => 'right'} %>
  </div>
</div>

<%= f.hidden_field :scale_tags %>

<script type="text/javascript">

  var scaleTags = {};
  $('input#tags_scale_tags').val(JSON.stringify(scaleTags));

  $('.scale-tag-button').click(function() {
    var scaleId = $(this).data('scaleId').toString();
    var scaleValue = $(this).data('scaleValue').toString();
    if (scaleTags[scaleId] !== scaleValue) {
      scaleTags[scaleId] = scaleValue;
      $('[data-scale-id=' + scaleId + ']').removeClass('active');
      $(this).addClass('active');
    } else {
      delete scaleTags[scaleId]
      $(this).removeClass('active');
    }
    $('input#tags_scale_tags').val(JSON.stringify(scaleTags));
  });

  $('.new-scale-term').keyup(function() {
    var scaleSide = $(this).data('scaleSide').toString();
    var scaleTerm = $(this).val();
    if (scaleTags['new_scale'] == undefined) scaleTags['new_scale'] = {};
    scaleTags['new_scale'][scaleSide] = scaleTerm;
    $('input#tags_scale_tags').val(JSON.stringify(scaleTags));
  });
</script>

app/views/tags/index.html.erb
<h1>Show Tags</h1>

<div class="record card">
  <div class="card-body">
    <h5 class="card-title"><%= @record.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @record.creator %></h6>
    <p class="card-text">
      <% @record.free_tags.each do |tag| %>
        <span class="badge badge-pill badge-secondary"><%= tag.term %></span>
      <% end %>
    </p>
    <p class="card-text">
      <% @record.scale_tags.each do |tag| %>
        <span class="badge badge-pill badge-secondary"><%= "#{tag.scale_left} – #{tag.scale_right}: #{tag.value}" %></span>
      <% end %>
    </p>

    <%= link_to "Link", @record.url, class: "btn btn-primary card-link" %>
    <%= link_to "Add more tags", new_record_tag_path(@record), class: "card-link" %>
  </div>
</div>

<%= link_to "Back to records", records_path %>

app/views/tags/new.html.erb
<h1>Add Tags</h1>

<%= form_for :tags, as: :post, url: record_tags_path(@record) do |f| %>

  <%= render 'free_tags_form', f: f %>
  <%= render 'scale_tags_form', f: f %>

  <%= f.submit 'Add tags', class: "btn btn-primary" %>

  <%= link_to 'Back', record_tags_path(@record) %>
<% end %>